[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "repopy"
version = "0.4.1"
description = "A modular CLI workspace initializer and cloning automation tool."
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}

authors = [
    {name = "Janitha Manatunga", email = "janithamanatunga@gmail.com"}
]

classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: MIT License",
]

[project.urls]
Homepage = "https://github.com/manatunga/repopy"
Repository = "https://github.com/manatunga/repopy"
"Bug Tracker" = "https://github.com/manatunga/repopy/issues"

[project.scripts]
repopy = "repopy.__main__:main"

[tool.pytest.ini_options]
pythonpath = ["src"]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "if __name__ == .__main__.:",
]

[tool.setuptools.package-data]
repopy = ["py.typed"]